# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

source 'https://github.com/aliyun/aliyun-specs.git'
source 'https://github.com/CocoaPods/Specs.git'

target 'DinCoreExample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for DinCoreExample

  # AES加解密
  pod 'CryptoSwift'
  # UDP库
  pod 'CocoaAsyncSocket'
  # gcd timer
  pod "ZYGCDTimer"
  # 压缩库 for os.log
  pod 'SSZipArchive'

  # DNS
  pod 'AlicloudHTTPDNS', '2.0.6'
  # 数据库存储
  pod 'Objective-LevelDB'
  # 网络库
  pod 'Moya'
  # 序列化/类型转化
  pod 'HandyJSON'
  # 压缩/解压缩
  pod 'Snappy'
  # 响应式编程库
  pod 'RxSwift'
  pod 'RxCocoa'
  # 七牛
  pod 'Qiniu'
  # websocket
  pod 'Starscream', '3.1.1'
  # YYModel
  pod 'YYModel'

  pod 'DinSupport', :path => '../../../DinSupport/'

#  pod 'DinCore', :path => '../../'
  pod 'DinCore/DinPanel', :path => '../../'
  pod 'DinCore/DinLiveStreaming', :path => '../../'
  pod 'DinCore/DinStorageBattery', :path => '../../'

  target 'DinCoreExampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'DinCoreExampleUITests' do
    # Pods for testing
  end

end

post_install do |installer|
  installer.generated_projects.each do |project|
    project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '11.0'

            config.build_settings['CODE_SIGN_IDENTITY'] = ''
            config.build_settings['CODE_SIGNING_ALLOWED'] = "NO"
            config.build_settings['CODE_SIGNING_REQUIRED'] = "NO"
         end
    end
  end
end
